name: Sphinx documentation

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "main"
    workflow_dispatch:
        branches:
            - "main"

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.9
              uses: actions/setup-python@v3
              with:
                  python-version: "3.9"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                  pip install sphinx sphinx_rtd_theme myst_parser
			- name: Build documentation
              run: |
                  make html
			- name: Deploy documentation to GitHub Pages (branch: gh-pages)
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_branch: gh-pages
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs/sphinx/_build/html
                  force_orphan: true
